### ISSUE TITLE
Dockerfile: please switch from scratch to something slightly fatter

### ISSUE THREAD

**Issue by bootc** [stackrox/kube-linter#114]
**Description of the problem/feature request**
The Docker image for kube-linter includes nothing but kube-linter itself. This makes for a really small image, but make it unusable in some CI systems such as GitLab CI which require some kind of shell to be present.

**Description of the existing behavior vs. expected behavior**
Without a shell, GitLab CI is unable to use the image to run kube-linter during a CI pipeline. Using a different base image such as the Alpine ones provides enough of a shell to allow it to work.

**Comment by viswajithiii** [comment]
Closing since this is fixed!

**Comment by bootc** [comment]
Thank you!
