### ISSUE TITLE
Can't Make Build[BUG]

### ISSUE THREAD

**Issue by brendan-s1** [stackrox/kube-linter#116]
**System info:**
 - OS: Ubuntu 18.04

**Describe the bug**
When i attempt to 'Make Build' i get the following error:

env: ‘Files’: No such file or directory
Makefile:7: recipe for target 'deps' failed
make: *** [deps] Error 127

I have deps installed, i verified.

**To Reproduce**
Steps to reproduce the behavior: Run Make Build in the kube-linter directory.

**Comment by kreamkorokke** [comment]
Hi @brendan-s1! Could you paste the output of `make deps` as well? I tried to run make build on my end as well but I didn't have this error.
