### ISSUE TITLE
Installation on Windows 10

### ISSUE THREAD

**Issue by VenkateshSrini** [stackrox/kube-linter#123]
**Description of the problem/feature request**
Can you provide the instruction to install the KubeLinter on Windows 10 machine

**Additional context**
I would suggest the installation be provided as chocolatey package if possible

**Comment by viswajithiii** [comment]
Hi @VenkateshSrini, sorry about the late response. You should be able to download a Windows-compatible KubeLinter binary from the artifacts on our release: https://github.com/stackrox/kube-linter/releases/tag/0.1.6. Let us know if you have any trouble with that.

Re: the chocolatey package, that's definitely something we can look into, but will not be our top priority at this time.

**Comment by VenkateshSrini** [comment]
Thanks
