### ISSUE TITLE
[FEATURE_REQUEST] Please also push Docker images to a registry other than Docker Hub

### ISSUE THREAD

**Issue by bootc** [stackrox/kube-linter#125]
**Description of the problem/feature request**
Docker Hub's rate limits make using it difficult in some situations. Please also push the Docker images to another public registry so that people can avoid the Docker Hub rate limits.

**Description of the existing behavior vs. expected behavior**
The Docker images are only available at [`stackrox/kube-linter`](https://hub.docker.com/r/stackrox/kube-linter). Please also use one of the many other available public registries, such as (in no particular order) gcr.io, quay.io, AWS ECR Public, or even GitLab.

**Comment by viswajithiii** [comment]
Hi @bootc, thanks for bringing this up. We'll figure something out.

**Comment by janisz** [comment]
I think we can use quay as it's part of RedHat also ghcr should be easy to set up.
