### ISSUE TITLE
[FEATURE_REQUEST] Add `--exclude-paths` option to exclude linting files under those paths 

### ISSUE THREAD

**Issue by asilverman** [stackrox/kube-linter#127]
**Description of the problem/feature request**
Our project contains a `third_party` folder containing yaml files that do not concern us, I would like an option to ignore all files under that path.

**Description of the existing behavior vs. expected behavior**
Currently this is not an option

**Additional context**
N\A

**Comment by viswajithiii** [comment]
Hi @asilverman, thanks for filing this issue! To confirm, is your current workflow to run `kube-linter lint .` at the root of a directory with a lot of files?

**Comment by nirav24** [comment]
@viswajithiii I'd interested to work on it if possible 🙂

**Comment by bootc** [comment]
I'd like to see something like this too, though ideally being able to configure the excluded paths using the `.kube-linter.yaml` configuration file. In my particular case I have a directory that contains some Kustomization patches as well as some upstream YAMLs; annotating those doesn't make sense (I'd like to avoid modifying the upstream YAML at all) so I'd just like to exclude them.

**Comment by schadom** [comment]
Please add this feature. We also need this. Thank you

**Comment by rptx** [comment]
This feature would be useful to exclude upstream charts for which we don't want to make changes.

**Comment by chrislin22** [comment]
any progress on this? we need this feature as well...

**Comment by titanlien** [comment]
Any updates for this feature, I am looking this option as well.

**Comment by asilverman** [comment]
> Hi @asilverman, thanks for filing this issue! To confirm, is your current workflow to run `kube-linter lint .` at the root of a directory with a lot of files? 

Yes

**Comment by chrislin22** [comment]
> > Hi @asilverman, thanks for filing this issue! To confirm, is your current workflow to run `kube-linter lint .` at the root of a directory with a lot of files?
> 
> Yes

same here

**Comment by titanlien** [comment]
Hi @begs Did you ever try `--ignore-paths` in v0.6.0 version? It should work.

**Comment by begs** [comment]
> Hi @begs Did you ever try `--ignore-paths` in v0.6.0 version? It should work.

Hi @titanlien! Yes, I haven't been able to make it work.

```
$ kube-linter version
0.6.0
```

I have tried including a path to `ignorePaths` in the config and with the `--ignore-paths` flag, but it still shows errors from that path when I run `kube-lint lint .` from the repository root.

I have tried variations of global and relative path but with no luck. I have been able to exclude checks using the config file though, so it is definitely able to read the config.

There is someone else with the same issue [here](https://github.com/giantswarm/trivy-operator-app/pull/51#issuecomment-1432403707).

**Comment by wiktor-k** [comment]
> I have tried including a path to ignorePaths in the config and with the --ignore-paths flag, but it still shows errors from that path when I run kube-lint lint . from the repository root.
>
> I have tried variations of global and relative path but with no luck. I have been able to exclude checks using the config file though, so it is definitely able to read the config.

Sounds like this issue is related: https://github.com/stackrox/kube-linter/issues/500 (FYI I've got the same problem, `ignorePaths` doesn't seem to apply).

**Comment by jumbosushi** [comment]
@janisz Looks like the fix landed with #515. Can we close this issue & cut new bug fix release?

**Comment by janisz** [comment]
Sure, I'm waiting for one more PR and will cut release tomorrow. Thanks for pointing this out.
