### ISSUE TITLE
Comparison with Pluto

### ISSUE THREAD

**Issue by chainhead** [stackrox/kube-linter#130]
How does `kube-linter` compare with `pluto`? https://github.com/FairwindsOps/pluto

**Comment by bitva77** [comment]
not trying to be rude but the description of both projects highlights the differences.  Pluto is focused on API versions - kube-linter is focused on best practices.

Like if I have a Deployment manifest that uses `apiVersion: apps/v1beta1` - Pluto is going to complain about that.  kube-linter ain't going to complain.

Other side is that kube-linter will complain if you're running your container as root, pluto won't.

I guess running deprecated API versions isn't really best practice but...

**Comment by rbren** [comment]
https://github.com/FairwindsOps/polaris is a more analogous project, focused on best practices.

**Comment by viswajithiii** [comment]
Hi @chainhead, thanks for your question.

As @bitva77 said, Pluto is focused just on API versions. Note that KubeLinter _does_ support this as well. For example, we have a [built-in check](https://github.com/stackrox/kube-linter/blob/main/pkg/builtinchecks/yamls/no-extensions-v1beta.yaml) that ensures no usage of `extensions/v1beta`. However, that's our only built-in check in this category right now, and users will have to manually create more checks. It would definitely be in scope for KubeLinter to have a check similar to Pluto, that lets you just say "flag deprecated API versions" without users having to manually list out the objects they want to forbid. I've filed #132 to track this.

Thanks again for filing this. And thanks @bitva77 and @rbren for responding. 🙂

**Comment by sudermanjr** [comment]
Maintainer of Pluto here, I was going to say that exact thing. 

Just checking out KubeLinter today and ran it against our pluto repo just to see.

```
pkg/finder/testdata/deployment-extensions-v1beta1.yaml: (object: yaml-namespace/utilities extensions/v1beta1, Kind=Deployment) disallowed API object found: extensions/v1beta1, Kind=Deployment (check: no-extensions-v1beta, remediation: Migrate to using the apps/v1 API versions for these objects. See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more details.)
```

Pretty cool stuff so far. Thanks!
