### ISSUE TITLE
[FEATURE_REQUEST] Add support for using a non-default clientSchema

### ISSUE THREAD

**Issue by aiyengar2** [stackrox/kube-linter#141]
**Description of the problem/feature request**
A clear and concise description of the problem, or the proposed new feature.

Currently, the scheme used to unmarshall the JSON objects from the manifest is hard-coded to `scheme.Scheme` here:
https://github.com/stackrox/kube-linter/blob/a64df58c92e9dcab418e2cc9f1e796eae70b97fa/pkg/lintcontext/parse_yaml.go#L33

This scheme is used to deserialize the k8s manifests, so any valid k8s objects that are not recognized by the default scheme (e.g. CustomResources) are unable to be deserialized. 

Instead, would it be possible to modify the function signature for `CreateContexts` to optionally take in a `*runtime.Scheme`?

https://github.com/stackrox/kube-linter/blob/a64df58c92e9dcab418e2cc9f1e796eae70b97fa/pkg/lintcontext/create_contexts.go#L23

From a CLI context, this would probably be set to `nil` or `scheme.Scheme`, but this would be helpful for other packages consuming this code.

**Additional context**

Probably a followup for https://github.com/stackrox/kube-linter/issues/119.

I've been trying to consume kube-linter to create a Helm chart testing framework and I hope to upstream it at some point. Making a one-line change to the code linked above seems to be the only blocker, but if this issue is resolved I can go back to consuming upstream directly instead of forking.

**Comment by viswajithiii** [comment]
@aiyengar2 This makes sense to me. Would you be able to send a PR?

**Comment by aiyengar2** [comment]
@viswajithiii done! https://github.com/stackrox/kube-linter/pull/144

**Comment by viswajithiii** [comment]
Closing since this is done.
