### ISSUE TITLE
[BUG]: Unable to use kube-linter in windows

### ISSUE THREAD

**Issue by pioust1** [stackrox/kube-linter#161]
**System info:**
 - Windows

**Describe the bug**
C:\XXX\Kube-Linter>kube-linter lint kube-test1.yaml
**Error: UNEXPECTED: failed to load built-in checks: loading file dangling-service.yaml: open yamls\dangling-service.yaml: file does not exist**

**To Reproduce**
Installed kube-linter in windows and it failed with the above issue

**Comment by viswajithiii** [comment]
Thanks @pioust1 for filing this! I've sent out #162 to fix.
