### ISSUE TITLE
[FEATURE_REQUEST] Add check for trusted sources

### ISSUE THREAD

**Issue by rrati** [stackrox/kube-linter#182]
**Description of the problem/feature request**
Docker images can be pulled from almost any registry without any verification that the registry is trusted.  Adding a check that allows the user to specify a list of repositories they consider trusted can help identify images being pulled from a registry that isn't trusted.

**Description of the existing behavior vs. expected behavior**
Nothing happens now.  When this check is implemented, the user can define a list of registry urls that are deemed trustworthy and any image not coming from that registry would be fail the check,

**Comment by viswajithiii** [comment]
Makes sense to me.

**Comment by Priyankasaggu11929** [comment]
@rrati, @viswajithiii, thanks for creating the issue. I'm picking this up & will be working on the implementation. Thank you!

**Comment by janisz** [comment]
It was closed by #191
