### ISSUE TITLE
[FEATURE_REQUEST] Add check for trusted tags

### ISSUE THREAD

**Issue by rrati** [stackrox/kube-linter#183]
**Description of the problem/feature request**
An image tag may become untrustworthy if it is found to have a severe bug/vulnerability or has been discovered to have been built from compromised sources.  Alternately a user may want to only allow explicit tags to be deployed in their workloads, either to disallow something like the latest tag, or to specify a list of approved tags for an image.

**Description of the existing behavior vs. expected behavior**
If enabled, this check would fail any manifests that use tags that are not configured as acceptable by the check.  This could be a whitelist or a blacklist.

**Comment by viswajithiii** [comment]
Makes sense. This is very similar to #182. I wonder if we should have a template that takes in a list of image names, allowing the user to specify a regex so they can specify a registry, or a tag, or a combination of both. The template can take two lists: an `allowlist` and a `blocklist`, and we can say something like:
1. If `allowlist` is specified, the image must match at least one regex from the allowlist.
2. If `blocklist` is specified, the image must not match any regex from the blocklist.

(This implies that the `blocklist` takes precedence -- if an image is in both the `allowlist` and `blocklist`, then the check will still be violated. That seems like a better stance to take, to err on the side of more caution.)

Let me know what you think. Such a template would solve both #182 and this, and we could then just implement checks for these.

**Comment by rrati** [comment]
I was thinking this was very similar to #182 as I was writing it.  A regex may actually work well here with a single template that will do the work.

I do wonder if we should be more exacting in the template though.  When we allow allow and block lists together, things can get messy.  What the template only allowing one or the other to be specified, and if the user wants an allow and a block list then they define to different checks using the same template?  Then there's no magic to figure out which takes precidence.

**Comment by viswajithiii** [comment]
> I was thinking this was very similar to #182 as I was writing it. A regex may actually work well here with a single template that will do the work.
> 
> I do wonder if we should be more exacting in the template though. When we allow allow and block lists together, things can get messy. What the template only allowing one or the other to be specified, and if the user wants an allow and a block list then they define to different checks using the same template? Then there's no magic to figure out which takes precidence.

Makes sense. From thinking through it, there is no flexibility lost by having them in separate templates.

**Comment by Priyankasaggu11929** [comment]
@rrati, @viswajithiii, thanks for creating the issue. I'm picking this up & will be working on the implementation. Thank you!

**Comment by janisz** [comment]
It was closed by #191
