### ISSUE TITLE
[FEATURE_REQUEST] Add check for UpdateStrategy

### ISSUE THREAD

**Issue by rrati** [stackrox/kube-linter#184]
**Description of the problem/feature request**
An updateStrategy of RollingUpdate along with a minimum unavailable helps ensure a service can be upgraded without disrupting service.  Users may have other configurations they determine would allow for safe upgrades of their service.  The desire here is to implement a check that validates an object has an acceptable upgrade strategy.

**Description of the existing behavior vs. expected behavior**
Once implemented the check would fail any object that does not conform to the update strategy.  By default, rollingUpdate and maxUnavailable for 1 (or 3?) seem to make sense.

**Comment by viswajithiii** [comment]
This is great! Definitely would be a helpful addition.

**Comment by rrati** [comment]
I am currently working on this ticket
