### ISSUE TITLE
[FEATURE_REQUEST] force color configuration

### ISSUE THREAD

**Issue by glehmann** [stackrox/kube-linter#205]
**Description of the problem/feature request**
Add a configuration (flag, env var, …) to force the colored output

**Description of the existing behavior vs. expected behavior**
When not run from a terminal, there is no color in the output. This is usually fine, except in a few cases, like during continuous integration.

**Additional context**
I'm running kube-linter from gitlab-ci, and would love to have some colors in the output!

**Comment by viswajithiii** [comment]
This seems totally reasonable!

**Comment by lpmatos** [comment]
Same interest!

**Comment by glehmann** [comment]
Note: in the mean time we can rely on this trick to force the color output:

~~~
script --return --quiet -c "kube-linter lint /my/files" /dev/null
~~~

source: https://stackoverflow.com/questions/1401002/how-to-trick-an-application-into-thinking-its-stdout-is-a-terminal-not-a-pipe

**Comment by janisz** [comment]
It looks like we need to apply this snippet to our command https://github.com/fatih/color#disableenable-color
