### ISSUE TITLE
[BUG] Wrong artifacts locations in SARIF reports for Helm if Chart and containing directory have different names

### ISSUE THREAD

**Issue by rm3l** [stackrox/kube-linter#212]
**System info:**
 ```
 ❯ kube-linter version
development
```
 - Ubuntu Linux 21.04

**Describe the bug**
Hi there!
I was trying to run KubeLinter against a set of Helm Charts and upload the generated SARIF reports to GitHub Code Scanning.
I noticed the artifacts locations in the generated SARIF reports use the Helm Chart names in the relative paths, which obviously could not be resolved by GitHub Code Scanning because the Charts live in directories named differently.
Maybe I missed something, but as mentioned in https://github.com/helm/helm/issues/1979 and [helm/helm-www#113](https://github.com/helm/helm-www/pull/1113/files#diff-c31785a9696cc3162b9e6837ee45b28b5eaa978f62970adecd6c2e294d5b7ea8), this constraint on the directory name has been removed in Helm and is no longer a requirement for Helm Charts.

**To Reproduce**
Run the following commands:

```sh
# Create a sample Helm Chart
helm create my-helm-chart

# Rename the containing directory
mv my-helm-chart my-helm-chart-directory

# kube-linter
kube-linter lint my-helm-chart-directory --format sarif \
  | jq -r '.runs[].results[].locations[].physicalLocation.artifactLocation.uri' \
  | uniq
```

The `kube-linter` command above returns the following relative paths, which cannot be resolved by tools like GitHub Code Scanning.
```
my-helm-chart/templates/deployment.yaml
my-helm-chart/templates/tests/test-connection.yaml
```

**Sample YAML input**
N/A

**Expected behavior**
I would expect the artifact locations paths to use the containing directory. In the sample commands above, I would expect the following paths instead:
```
my-helm-chart-directory/templates/deployment.yaml
my-helm-chart-directory/templates/tests/test-connection.yaml
```

**Additional context**
Below is a screen capture illustrating how GitHub Code Scanning is unable to display a preview of the YAML resources, because it cannot resolve the paths reported in the SARIF reports:
![Screenshot from 2021-09-20 00-07-11](https://user-images.githubusercontent.com/593208/133944574-3d08f808-3c3d-4e15-9563-534d1f91e883.png)

**Comment by msugakov** [comment]
Thanks again for the detailed description and steps to reproduce, Armel!
I published today a PR to address this issue https://github.com/stackrox/kube-linter/pull/215
Will let you know once it's released.

**Comment by msugakov** [comment]
The fix for this was merged as part of https://github.com/stackrox/kube-linter/pull/226
A new release is still pending. I'll post an update when the new version with the fix is available.

**Comment by rm3l** [comment]
Thanks again, Misha!
