### ISSUE TITLE
[FEATURE_REQUEST] Recognise batch/v1 CronJob as deployment-like

### ISSUE THREAD

**Issue by mjpieters** [stackrox/kube-linter#223]
**Description of the problem/feature request**
As of v1.21, `CronJob` has been upgraded to API version `batch/v1`. Could kube-linter please be upgraded to recognise this version?

See https://v1-21.docs.kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by viswajithiii** [comment]
Thanks for filing! Between #224 and #225, this should be fixed. We'll be putting out a new release soon after these are merged.
