### ISSUE TITLE
[FEATURE_REQUEST] Add "pretty-print" option

### ISSUE THREAD

**Issue by frerikandriessen** [stackrox/kube-linter#229]
**Description of the problem/feature request**
I have kube-linter running in my CI-CD pipeline, but all the errors it collects are dumped on one long line which makes it difficult to parse by eye.
I could of course copy the output and run it by `jq`, but it would be nice if the tool itself has that option. 

Probably adding a `--format pretty-json` and `--format pretty-sarif` could already work, but a separate `--pretty-print` option would also work nicely I think.

Is this manageable? I would be willing to take a crack at it myself, if you think it's a good addition to the tool.

**Comment by viswajithiii** [comment]
Hi @frerikandriessen, thanks for filing this issue! This option is easy enough to add code-wise, the tricky thing -- which makes me hesitant -- is how exactly to provide this configurability without creating a proliferation of flags.

Couple of questions to help me understand the use-case:
1. Why are you running with `--format json` in your CI/CD pipeline?
2. Do you have `jq` in your CI/CD pipeline right now (in which case, you can just do `kube-linter lint .... | jq` to get this result), or would you need to install it?
2. The SARIF output is not intended for human consumption, so I don't see why a `pretty-sarif` is required. Or do you see a use-case for it?

**Comment by frerikandriessen** [comment]
1. I'm running this in a Tekton pipeline (https://tekton.dev/), but while task-wrapping this tool they did not provide the `plain` option. I've corrected that now: https://github.com/tektoncd/catalog/pull/831. For my use-case `plain` is sufficient.
2. If `plain` was not sufficient however, it would be quite difficult to parse the output to `jq`. I attempted this at first but I was really fighting against the whole structure of how Tekton is set up. This prompted me to fix it at the source, but again, this was before I realized that `plain` was an option.
3. I can see wanting to analyse by eye a specific part that gives errors in your sarif-processing tool, but it's not that strong of a use-case. My suggestion was based on a misunderstandig of the sarif format.

So all in all, after learning more about it, I'm satisfied with the tool as is. 
Whenever I use json, I do like the option to be able to pretty-print it (especially since the `json` option gives info that you don't get via `plain`), but I can understand your fear of flag-creep if you add 'just this one'.

**Comment by viswajithiii** [comment]
Thanks, @frerikandriessen, for your thorough response. 🙂 I didn't realize `kube-linter` was on the Tekton catalog, that's cool!

For now, I will close this issue, but I will keep it in the back of my mind in case we get more requests for something like this.
