### ISSUE TITLE
Slack links do not allow sign up to Stackrox community slack workspace

### ISSUE THREAD

**Issue by danekantner** [stackrox/kube-linter#239]
Slack links do not allow sign up to Stackrox slack workspace

The links to the Slack workspace do not allow new users to sign up. 

https://www.stackrox.io/about/ and https://www.stackrox.io/ both link to https://cloud-native.slack.com/archives/C01TDE3GK0E which are both SIGN IN pages, not pages that allow new users to associate with that workspace. 

A user whom attempts to SSO to this workspace gets the error "xyz@abc.com doesn’t have an account on this workspace."

**Comment by Maddosaurus** [comment]
Thank you for pointing that out!  
On closer inspection, this link points right to the `#stackrox` channel inside the CNCF Slack, hence the login.
I'll look into generating the correct link.

In the meantime, feel free to join the CNCF Slack via https://slack.cncf.io/ and then joining `#stackrox` afterwards.  
In any case, welcome! 🎉

**Comment by janisz** [comment]
@Maddosaurus any update on this? Should we move with kube-linter to cncf slack?

**Comment by Maddosaurus** [comment]
@danekantner I'd like to announce that we updated the instructions to includeways for singing up as well as for joining channels for existing users: https://www.stackrox.io/slack/ 🎉 

@janisz thank you for pinging me on an update!
The CNCF Slack certainly is one of the biggest and most active Kubernetes-related Slack spaces out there. 
Whether we should move kube-linter over to it or not, is up the kube-linter community, I'd say. 
Generally, it always introduces friction when moving the whole community somewhere else.
How about we create a channel on the CNCF Slack to be available there and see what happens? I expect there to be a bit of traffic that could be redirected to the kube-linter Slack.

For now, I'll close this issue as we've updated the instructions page.
@danekantner Feel free to reopen the ticket if you'd like to discuss the new instructions!
