### ISSUE TITLE
[BUG] Change tags to be of the form vx.y.z instead of x.y.z

### ISSUE THREAD

**Issue by viswajithiii** [stackrox/kube-linter#240]
This is required for `go get` to work correctly. Right now, the autogenerated go docs say we don't have a tagged version: https://pkg.go.dev/golang.stackrox.io/kube-linter

This will require updates to the automation, as well as to https://github.com/stackrox/kube-linter-action.

**Comment by janisz** [comment]
- https://github.com/stackrox/kube-linter/pull/497
