### ISSUE TITLE
[BUG]CPU and memory limit upper bound setting

### ISSUE THREAD

**Issue by fitiger** [stackrox/kube-linter#241]
Hi there, 

currently the CPU usage range doesn't work properly.
`- name: "maximum-memory"
  template: "memory-requirements"
  params:
    requirementsType: "limit"
    upperBoundMB: 1000
    lowerBoundMB: 100`

I checked the source code and found that the following function is incorrect. The value_in_range function will return true if the given value is in range. So, the function should raise an error when the return is false (not in the range) instead of true. Can you help correct the problem?

Thanks.

https://github.com/stackrox/kube-linter/blob/b614a5d808aaead38a4b92553a2f3fb738ec28db/pkg/templates/memoryrequirements/template.go#L22

**Comment by viswajithiii** [comment]
Hi @fitiger, this is working as intended. I can see why it's confusing, but the template was defined to allow people to specify the forbidden ranges, and not the allowed ranges. (You can get the behaviour you want by creating two checks, one with `lowerBoundMB` unspecified and `upperBoundMB: 100`, and the other with `lowerBoundMB: 1000` and `upperBoundMB` unspecified.) Hope that make sense!

**Comment by zhul-nnit** [comment]
Thanks for clarifying! The forbidden range makes sense, but it is really confusing when reading the documents.

It said, "Key: memory-requirements; Description: Flag containers with memory requirements in the given range" in the document. 

Maybe we can declare it clearly or use the allowed range.

**Comment by viswajithiii** [comment]
Hmm, do you have any suggestions for wording? The description _is_ accurate in that we do flag (flag = create violations) when the memory requirements are _in_ the range. Maybe we could add another sentence explicitly saying it's the forbidden range to be unambiguous.

**Comment by zhul-nnit** [comment]
I think "Specify the invalid/forbidden range for containers memory" or "M not in (lowerbound, upperbound]" would be more clear.

In the beginning, I saw the lower bound and upper bound and intuitively thought they should be valid ranges as most functions did. Also, there is no reason to lower bound and upper bound together when it refers to a forbidden range (we always want to make sure apps wouldn't run out of memory).

**Comment by viswajithiii** [comment]
> I think "Specify the invalid/forbidden range for containers memory" or "M not in (lowerbound, upperbound]" would be more clear.
> 
> In the beginning, I saw the lower bound and upper bound and intuitively thought they should be valid ranges as most functions did. Also, there is no reason to lower bound and upper bound together when it refers to a forbidden range (we always want to make sure apps wouldn't run out of memory).

Makes sense. We can do that.

It's a good point that we would typically not have both lower bound and upper bound specified -- people will most likely specify just one in practice. It's just that this is required to allow people to express everything. For example, our default policy has them both set to `0`, which is the only way to forbid people from having it set to 0 (which is interpreted by kube as "no limit").
