### ISSUE TITLE
[FEATURE_REQUEST] add support to check certain annotations are not used

### ISSUE THREAD

**Issue by sagar-shah-uipath** [stackrox/kube-linter#244]
**Description of the problem/feature request**
We wanna make sure that some developers don't use certain annotations in code base because that can cause deployments to restart.
E.g - Stakater provides `reloader.stakater.com/auto`, whenever any deployment/job has that annotation attached to it, they get restarted whenever any config or secret gets changed in namespace. In our use case, we wanna make sure nobody uses `reloader.stakater.com/auto` annotation bcz otherwise it will keep on restarting our deployments if config gets changed frequently

Request is similar to required-annotations, but what we need here different is this annotation should not be present anywhere in any resources.

**Comment by viswajithiii** [comment]
Thanks @sagar-shah-uipath for filing this issue! I've added it to our roadmap.
