### ISSUE TITLE
[BUG] kube-linter reports violations for no-liveness-probe in initContainer

### ISSUE THREAD

**Issue by sagar-shah-uipath** [stackrox/kube-linter#261]
**System info:**
 - All OS

**Describe the bug**
- We came across a bug with kube-linter where kube-linter reports violations for no-liveness-probe . Ideally it should not show violations for initContainers since k8s does not support adding liveness probe for initContainers but in our case, it is reporting violations for initContainers as well

**To Reproduce**
- Run kube-linter for any deployment that has initContainer where liveness probe is not configured

**Sample YAML input**
If applicable, sample YAML input which reproduces the issue.

**Expected behavior**
- It should not show violation for initContainer
https://kube-linter.slack.com/archives/C01ASRW6Y8L/p1643282582226739

**Comment by janisz** [comment]
Nice catch! The bug lives in `livenessprobe/template.go` which calls `util.PerContainerCheck` that iterates over all containers. The solution will be to create a version of this util that iterates but only thru non init containter.

https://github.com/stackrox/kube-linter/blob/e0525ba399bd15c163380295d6e404dff62250b7/pkg/templates/livenessprobe/template.go#L27

https://github.com/stackrox/kube-linter/blob/29fb15c48aa2aa10ec2f6daf9d1fba3aba02310e/pkg/templates/util/per_container_check.go#L21

https://github.com/stackrox/kube-linter/blob/29fb15c48aa2aa10ec2f6daf9d1fba3aba02310e/pkg/extract/customtypes/pod_spec.go#L25-L27

@sagar-shah-uipath Would you like to provide a patch for this?

**Comment by dhaus67** [comment]
I've taken this on @sagar-shah-uipath for your information, also removing the init-container check for readiness probe.
