### ISSUE TITLE
[FEATURE_REQUEST] Please provide an example of programatic use

### ISSUE THREAD

**Issue by alexec** [stackrox/kube-linter#270]
**Description of the problem/feature request**

I'd like to embed kube linter.

**Description of the existing behavior vs. expected behavior**

N/A

**Additional context**

Just some docs.

**Comment by rumstead** [comment]
hey @alexec - long time no chat since kubecon. we use kube-linter in our ci pipelines, what kind of examples are you looking for? I am sure I can provide some.

**Comment by alexec** [comment]
I'd like to embed kube-linter is Argo CD to surface linting issues in the UI. How can I do that?

**Comment by rumstead** [comment]
Have you tried:

1. Multistage the kube-linter binary into the argo cd image
2. run the kube-linter command in the repo-server where the manifests live? you will have to template them out first though

**Comment by alexec** [comment]
https://github.com/argoproj/argo-cd/issues/8962

**Comment by janisz** [comment]
@alexec I prepared small in code usage example. Is it what you are looking for?

```go
package in_code_usage

import (
	"os"
	"path"
	"testing"

	"github.com/stretchr/testify/assert"

	"golang.stackrox.io/kube-linter/pkg/builtinchecks"
	"golang.stackrox.io/kube-linter/pkg/checkregistry"
	"golang.stackrox.io/kube-linter/pkg/lintcontext"
	"golang.stackrox.io/kube-linter/pkg/run"

	// Register templates
	_ "golang.stackrox.io/kube-linter/pkg/templates/all"
)

func TestInCodeUsage(t *testing.T) {

	checkRegistry := checkregistry.New()
	err := builtinchecks.LoadInto(checkRegistry)
	assert.NoError(t, err)

	enabledChecks := []string{"latest-tag"}

	for file, status := range map[string]run.CheckStatus{
		"/src/github.com/stackrox/kube-linter/tests/checks/host-pid.yml":   run.ChecksPassed,
		"/src/github.com/stackrox/kube-linter/tests/checks/latest-tag.yml": run.ChecksFailed,
	} {
		t.Run(file, func(t *testing.T) {
			dirToLint := path.Join(os.Getenv("GOPATH"), file)
			lintCtxs, err := lintcontext.CreateContexts(dirToLint)
			assert.NoError(t, err)
			result, err := run.Run(lintCtxs, checkRegistry, enabledChecks)
			assert.NoError(t, err)
			assert.Equal(t, status, result.Summary.ChecksStatus)
		})
	}

}
```

**Comment by janisz** [comment]
@alexec Please reopen if something more could be done.
