### ISSUE TITLE
'make build' on clean Mac with GoLang fails with " /bin/bash: packr: command not found"

### ISSUE THREAD

**Issue by tdensmore** [stackrox/kube-linter#29]
Catalina 10.15.7
Golang: go version go1.15.3 darwin/amd64

~/w/r/kube-linter ❯❯❯brew install go
==> Downloading https://homebrew.bintray.com/bottles/go-1.15.3.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/6bd0119a31c1ae26831105490a67b97bed5d0fd2c6ad140cdf4c84aa7a315af2?response-content-disposition=attachment%3Bfilename%3D%22go-1.15.3.catalina.bottle.tar.gz%22&Policy=eyJTdGF0
######################################################################## 100.0%
==> Pouring go-1.15.3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.15.3: 9,780 files, 494.3MB
~/w/r/kube-linter ❯❯❯ make build
+ deps
go: downloading github.com/golangci/golangci-lint v1.30.0
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading k8s.io/api v0.19.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading k8s.io/apimachinery v0.19.2
go: downloading honnef.co/go/tools v0.0.1-2020.1.5
go: downloading k8s.io/cli-runtime v0.19.2
go: downloading github.com/stretchr/testify v1.6.1
go: downloading k8s.io/gengo v0.0.0-20200728071708-7794989d0000
go: downloading github.com/gobuffalo/packr v1.30.1
go: downloading k8s.io/client-go v0.19.2
go: downloading github.com/Masterminds/sprig/v3 v3.1.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/googleapis/gnostic v0.4.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
go: downloading github.com/gobuffalo/envy v1.7.1
go: downloading sigs.k8s.io/kustomize v2.0.3+incompatible
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: downloading k8s.io/klog/v2 v2.2.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading k8s.io/kube-openapi v0.0.0-20200805222855-6aeccd4b50c6
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/Masterminds/semver/v3 v3.1.0
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading google.golang.org/protobuf v1.24.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.0.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/go-logr/logr v0.2.0
go: downloading github.com/huandu/xstrings v1.3.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/spf13/cobra v1.0.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/gobuffalo/packd v0.3.0
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/google/go-cmp v0.5.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading helm.sh/helm/v3 v3.3.4
go: downloading github.com/joho/godotenv v1.3.0
go: downloading golang.org/x/tools v0.0.0-20200724022722-7017fd6b1305
go: downloading github.com/mitchellh/reflectwalk v1.0.0
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading k8s.io/utils v0.0.0-20200729134348-d5654de09c73
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/spf13/viper v1.7.0
go: downloading golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/rogpeppe/go-internal v1.6.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading github.com/golangci/revgrep v0.0.0-20180526074752-d9c87f5ffaf0
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/imdario/mergo v0.3.8
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/go-critic/go-critic v0.5.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/go-xmlfmt/xmlfmt v0.0.0-20191208150333-d5b6f63a941b
go: downloading k8s.io/apiextensions-apiserver v0.18.8
go: downloading github.com/spf13/jwalterweatherman v1.0.0
go: downloading github.com/stretchr/objx v0.2.0
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/golangci/check v0.0.0-20180506172741-cfe4005ccda2
go: downloading github.com/ssgreg/nlreturn/v2 v2.0.1
go: downloading github.com/Masterminds/goutils v1.1.0
go: downloading github.com/Djarvur/go-err113 v0.0.0-20200511133814-5174e21577d5
go: downloading github.com/securego/gosec/v2 v2.4.0
go: downloading github.com/golangci/errcheck v0.0.0-20181223084120-ef45e06d44b6
go: downloading github.com/uudashr/gocognit v1.0.1
go: downloading github.com/timakin/bodyclose v0.0.0-20190930140734-f7f2e9bca95e
go: downloading github.com/golangci/gofmt v0.0.0-20190930125516-244bba706f1a
go: downloading mvdan.cc/interfacer v0.0.0-20180901003855-c20040233aed
go: downloading github.com/maratori/testpackage v1.0.1
go: downloading github.com/ryancurrah/gomodguard v1.1.0
go: downloading github.com/quasilyte/regex/syntax v0.0.0-20200407221936-30656e2c4a95
go: downloading github.com/go-toolsmith/astequal v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200622214017-ed371f2e16b4
go: downloading github.com/go-toolsmith/astfmt v1.0.0
go: downloading github.com/tdakkota/asciicheck v0.0.0-20200416190851-d7f85be797a2
go: downloading mvdan.cc/gofumpt v0.0.0-20200709182408-4fd085cb6d5f
go: downloading github.com/sonatard/noctx v0.0.1
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading github.com/golangci/unconvert v0.0.0-20180507085042-28b1c447d1f4
go: downloading github.com/golangci/prealloc v0.0.0-20180630174525-215b22d4de21
go: downloading github.com/sourcegraph/go-diff v0.5.3
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading github.com/jingyugao/rowserrcheck v0.0.0-20191204022205-72ab7603b68a
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.3
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/golangci/misspell v0.0.0-20180809174111-950f5d19e770
go: downloading github.com/matoous/godox v0.0.0-20190911065817-5d6d842e92eb
go: downloading github.com/gostaticanalysis/analysisutil v0.0.3
go: downloading golang.org/x/mod v0.3.0
go: downloading github.com/go-toolsmith/strparse v1.0.0
go: downloading mvdan.cc/lint v0.0.0-20170908181259-adc824a0674b
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/go-toolsmith/astcopy v1.0.0
go: downloading github.com/golangci/maligned v0.0.0-20180506175553-b1d89398deca
go: downloading github.com/go-openapi/spec v0.19.3
go: downloading github.com/golangci/dupl v0.0.0-20180902072040-3e9179ac440a
go: downloading github.com/gofrs/flock v0.7.1
go: downloading github.com/ultraware/funlen v0.0.2
go: downloading github.com/nishanths/exhaustive v0.0.0-20200708172631-8866003e3856
go: downloading github.com/ultraware/whitespace v0.0.4
go: downloading github.com/nbutton23/zxcvbn-go v0.0.0-20180912185939-ae427f1e4c1d
go: downloading github.com/quasilyte/go-ruleguard v0.1.2-0.20200318202121-b00d7a75d3d8
go: downloading github.com/go-toolsmith/typep v1.0.2
go: downloading google.golang.org/appengine v1.6.5
go: downloading github.com/OpenPeeDeeP/depguard v1.0.1
go: downloading github.com/mattn/go-colorable v0.1.7
go: downloading github.com/denis-tingajkin/go-header v0.3.1
go: downloading github.com/smartystreets/goconvey v1.6.4
go: downloading github.com/go-toolsmith/pkgload v1.0.0
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/golangci/go-misc v0.0.0-20180628070357-927a3d87b613
go: downloading github.com/golangci/lint-1 v0.0.0-20191013205115-297bf364a8e0
go: downloading github.com/jirfag/go-printf-func-name v0.0.0-20191110105641-45db9963cdd3
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: downloading github.com/bombsimon/wsl/v3 v3.1.0
go: downloading github.com/shazow/go-diff v0.0.0-20160112020656-b6b7b6733b8c
go: downloading github.com/onsi/ginkgo v1.13.0
go: downloading github.com/golangci/goconst v0.0.0-20180610141641-041c5f2b40f3
go: downloading github.com/shurcooL/go-goon v0.0.0-20170922171312-37c2f522c041
go: downloading github.com/phayes/checkstyle v0.0.0-20170904204023-bfd46e6a821d
go: downloading github.com/golangci/gocyclo v0.0.0-20180528144436-0a533e8fa43d
go: downloading github.com/go-toolsmith/astcast v1.0.0
go: downloading github.com/daixiang0/gci v0.0.0-20200727065011-66f1df783cb2
go: downloading github.com/ryanrolds/sqlclosecheck v0.3.0
go: downloading github.com/nakabonne/nestif v0.3.0
go: downloading github.com/onsi/gomega v1.10.1
go: downloading github.com/go-openapi/swag v0.19.5
go: downloading github.com/golangci/ineffassign v0.0.0-20190609212857-42439a7714cc
go: downloading github.com/xeipuuv/gojsonschema v1.2.0
go: downloading github.com/go-openapi/jsonreference v0.19.3
go: downloading github.com/shurcooL/go v0.0.0-20180423040247-9e1955d9fb6e
go: downloading mvdan.cc/unparam v0.0.0-20190720180237-d51796306d8f
go: downloading github.com/tommy-muehle/go-mnd v1.3.1-0.20200224220436-e6f9a994e8fa
go: downloading github.com/evanphx/json-patch v4.9.0+incompatible
go: downloading github.com/cyphar/filepath-securejoin v0.2.2
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/mailru/easyjson v0.7.0
go: downloading sourcegraph.com/sqs/pbtypes v0.0.0-20180604144634-d3ebe8f20ae4
go: downloading github.com/jtolds/gls v4.20.0+incompatible
go: downloading github.com/kisielk/gotool v1.0.0
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading github.com/kyoh86/exportloopref v0.1.7
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
go: downloading github.com/tetafro/godot v0.4.8
go: downloading github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
go: downloading github.com/google/btree v1.0.0
go: downloading github.com/go-toolsmith/astp v1.0.0
go: downloading github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: downloading github.com/nxadm/tail v1.4.4
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
all modules verified
+ /Users/todd/workspace/replicated/kube-linter/.gobin/packr
packr
**/bin/bash: packr: command not found
make: *** [packr] Error 127**

**Comment by viswajithiii** [comment]
Hi @tdensmore, thanks for filing this. Definitely not expected. What are the contents of the `/Users/todd/workspace/replicated/kube-linter/.gobin` directory?

**Comment by viswajithiii** [comment]
Hi @tdensmore, I think I identified the issue. I've pushed a fix to `main`. Can you confirm if this is fixed after you pull?

**Comment by tdensmore** [comment]
Yep. 👍 Fixed.

**Comment by viswajithiii** [comment]
Awesome! Closing this issue.
