### ISSUE TITLE
[FEATURE_REQUEST]

### ISSUE THREAD

**Issue by rvillane** [stackrox/kube-linter#312]
**Description of the problem/feature request**
Allow kube-linter to run with exit-code 0 regardless of what issues were discovered

**Additional context**
I'm planning to add kube-linter to a CI/CD pipeline and it would be nice to have the output to let users understand what issues exist in their YAML files but without breaking build.  After a grace period, then we would consider enforcing kube-linter checks.

**Comment by stehessel** [comment]
You can ignore exit codes in most shells by doing something like

```
kube-linter ... || true
```

This does not seem like a need feature for kube-linter to me.

**Comment by viswajithiii** [comment]
Hi @rvillane, thanks for filing this issue. I would agree with @stehessel and recommend you take the `|| true` approach; this is quite standard for tools run in CI, and doesn't seem like something that's worth adding to `kube-linter`.
