### ISSUE TITLE
Unable to join slack

### ISSUE THREAD

**Issue by tspearconquest** [stackrox/kube-linter#420]
Hello,

I tried to join the Kube-Linter slack, but I don't have an @stackrox.com email address, and it doesn't appear to allow me to login using my existing work email nor my gmail account.

Can you please help me out?

Thanks in advance.

**Comment by rukletsov** [comment]
I was just able to log in using my personal email (gmail). I don't think we have any entry barriers so I'm curious what's happening here. When you've used your gmail account, have you tried it as email or google?

**Comment by tspearconquest** [comment]
Yes I was able to login today with my work email. Thanks!
