### ISSUE TITLE
[BUG] Annotations not used to ignore specific violations?

### ISSUE THREAD

**Issue by christopherwood** [stackrox/kube-linter#423]
Hello kube-linter folks,

I don't know if I'm reading the documentation correctly or what, but I'm having an issue where annotations are not understood in the same way that a config file is when running "kube-linter lint". Details below.

**System info:**

(Reproduced on both of these.)

Ubuntu 22.04:

$ uname -a
Linux DTSA-000002 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 22.04.1 LTS \n \l

$ go version
go version go1.18.1 linux/amd64

$ kube-linter version
0.5.0-0-g5b90391fdf

MacOS:

$ uname -a
Darwin iniquitous 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64 arm Darwin

$ sw_vers -productVersion
12.6

$ go version
go version go1.19.2 darwin/arm64

$ kube-linter version
0.5.0-6-g28f152eb67

**Describe the bug**

The annotations in the sample YAML input (d1.yml) are not used to ignore specific checks, but the same clauses in a config file are used.

https://github.com/stackrox/kube-linter/blob/main/docs/configuring-kubelinter.md#ignoring-violations-for-specific-cases

(This of course could be me misunderstanding the documentation.)

**To Reproduce**

$ kube-linter lint d2.yml 
KubeLinter 0.5.0-6-g28f152eb67

No lint errors found!
$ kube-linter lint d1.yml 
KubeLinter 0.5.0-6-g28f152eb67

d1.yml: (object: test1/test1 apps/v1, Kind=Deployment) container "testone1" does not have a read-only root file system (check: no-read-only-root-fs, remediation: Set readOnlyRootFilesystem to true in the container securityContext.)

d1.yml: (object: test1/test1 apps/v1, Kind=Deployment) container "testone1" is not set to runAsNonRoot (check: run-as-non-root, remediation: Set runAsUser to a non-zero number and runAsNonRoot to true in your pod or container securityContext. Refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for details.)

Error: found 2 lint errors
$ kube-linter lint d1.yml --config kube-linter-config.yml 
KubeLinter 0.5.0-6-g28f152eb67

No lint errors found!

**Sample YAML input**

Please see the attached files (I had to rename them to .txt to attach them):

d1.yml -- reproduces the issue
d2.yml -- passes "kube-lint lint" to be the "control group"
kube-linter-config.yml -- config file used to show that d1.yml can be made to pass "kubectl lint"

**Expected behavior**

I expected this (some spacing added for readability):

$ kube-linter lint d2.yml 
KubeLinter 0.5.0-6-g28f152eb67

No lint errors found!

$ kube-linter lint d1.yml
KubeLinter 0.5.0-6-g28f152eb67

No lint errors found!

$ kube-linter lint d1.yml --config kube-linter-config.yml 
KubeLinter 0.5.0-6-g28f152eb67

No lint errors found!

**Screenshots**

N/A, issue is demonstrated above in text form.

**Additional context**

N/A, can't think of any right now.

[d1.yml.txt](https://github.com/stackrox/kube-linter/files/9737101/d1.yml.txt)
[d2.yml.txt](https://github.com/stackrox/kube-linter/files/9737104/d2.yml.txt)
[kube-linter-config.yml.txt](https://github.com/stackrox/kube-linter/files/9737106/kube-linter-config.yml.txt)

**Comment by mil7** [comment]
Hi there,
I am also interested in [how to ignore violations for a specific case](https://github.com/stackrox/kube-linter/blob/main/docs/configuring-kubelinter.md#ignoring-violations-for-specific-cases). The documentation is too vague. Can you please clarify the case?

**Comment by mil7** [comment]
@christopherwood,
I managed to get your example working. Your approach is correct but also includes a typo:

`ignore.check.kube-linter.io/<rule>` 

must become 

`ignore-check.kube-linter.io/<rule>`.

I also provided a suggestion for a change in the docs https://github.com/stackrox/kube-linter/pull/491.
