### ISSUE TITLE
[BUG] --ignore-paths doesn't seem to do anything

### ISSUE THREAD

**Issue by begs** [stackrox/kube-linter#500]
Does `ignorePaths` work?

I have tried multiple variations of paths, both in the `.kube-linter.yaml` config and as a CLI flag but with no luck.

**Comment by mbaldessari** [comment]
FWIW I also tried different combinations of ignorePaths to no avail so far (both in a .kube-linter.yaml config file and via --ignore-paths arg)

**Comment by janisz** [comment]
Thanks for spotting this issue. I did poor job on code review but here is the fix: https://github.com/stackrox/kube-linter/pull/515
