### ISSUE TITLE
"Warning: no valid objects found."

### ISSUE THREAD

**Issue by JacksonRin** [stackrox/kube-linter#51]
what the follow error meannings when I do check
"Warning: no valid objects found."

**Comment by kreamkorokke** [comment]
Hi there! Thanks for posting the issue.
It means that while trying to parse the yaml files we didn't find any k8s object to run lint command against. You can try run it again with "-v" to see the load errors.

**Comment by JacksonRin** [comment]
yeah,what I got when add "-v" param like this:
"Warning: failed to load object from csspods.yaml: failed to decode: couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }"
