### ISSUE TITLE
how can I get all of the check rules of kube-linter

### ISSUE THREAD

**Issue by JacksonRin** [stackrox/kube-linter#52]
From the result of kube-linter check,I could only get the problem of my pod yaml.
How can I get all of the check rules of kube-linter?

**Comment by gaurav-nelson** [comment]
Thanks @JacksonRin 

https://github.com/stackrox/kube-linter/blob/main/docs/generated/checks.md lists all current checks. Does this answer your question?

**Comment by JacksonRin** [comment]
yes
