### ISSUE TITLE
release 0.6.1 was not completed

### ISSUE THREAD

**Issue by chenrui333** [stackrox/kube-linter#520]
👋 it looks like [release 0.6.1 was not completed](https://github.com/stackrox/kube-linter/actions/runs/4424365447/jobs/7758200006), raise an issue in here for some awareness. Thanks!

**Comment by janisz** [comment]
I'm sorry, maybe I need to better communicate it. I tried to release it but it turns out we need following PRs in order to release it properly with signatures. 
- #514
- #520

**Comment by chenrui333** [comment]
yeah, np. thanks @janisz!

**Comment by janisz** [comment]
It's there! Thanks for patience
