### ISSUE TITLE
0.6.2 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [stackrox/kube-linter#538]
👋 it looks like 0.6.2 release was not completed. 

relates to https://github.com/Homebrew/homebrew-core/pull/128068

**Comment by janisz** [comment]
My bad, forgot to click publish. Its there https://github.com/stackrox/kube-linter/releases/tag/v0.6.2

**Comment by chenrui333** [comment]
Thanks @janisz!

**Comment by janisz** [comment]
In the meantime we released 0.6.3
