### ISSUE TITLE
Enhancement: Don't expose SSH ports

### ISSUE THREAD

**Issue by IAmATeaPot418** [stackrox/kube-linter#70]
A check we should consider for KubeLinter is not to expose ssh ports as part of a deployment. @viswajithiii lmk your thoughts here.

**Comment by arghya88** [comment]
@viswajithiii this would just be a check `22` is specified in the `containerPort` ?

**Comment by viswajithiii** [comment]
> @viswajithiii this would just be a check if `22` is specified in the `containerPort` ?

@arghya88 That's right. We probably want to check the protocol is TCP as well.

When we implement it, we probably want a generic template for ports and protocols that takes in the port and protocols as params, and a specific check that specifies port = 22 and protocol = TCP.
